Finally able to use my mac!

diff --git a/scripts-james/helpers/get-secrets b/scripts-james/helpers/get-secrets
--- a/scripts-james/helpers/get-secrets
+++ b/scripts-james/helpers/get-secrets
@@ -3,41 +3,42 @@ set -eo pipefail
 
 # SECTION 1: THINGS THAT CAN BE DOWNLOADED ONCE, AND DO NOT CHANGE
 
-function 1p {
-	set +e
-	if [[ "$1" != "signin" && "$1" != "signout" && "$1" != "suspend" && "$1" != "reactivate" ]]; then
-		# Check if signed in by looking at vaults (takes the least time to load).
-		if ! op list vaults > /dev/null 2>&1; then
-			# Not logged in. Try to log in if not already logged in
-			if [[ ! -f "$HOME/.op/config" && ! -f "$HOME/.config/op/config" ]]; then
-				# Oh wait, this machine has never been signed in on!
-				echo '/!\ Do not type your master password yet! /!\'
-				op --cache signin costian jamescostian@gmail.com
-			fi
-			eval $(op --cache signin costian)
-		fi
+set +e
+# Check if signed in by looking at vaults (takes the least time to load).
+if ! op list vaults > /dev/null 2>&1; then
+	# Not logged in. Try to log in if not already logged in
+	if [[ ! -f "$HOME/.op/config" && ! -f "$HOME/.config/op/config" ]]; then
+		# Oh wait, this machine has never been signed in on!
+		echo '/!\ Do not type your master password yet! /!\'
+		op --cache signin costian jamescostian@gmail.com
 	fi
-	set -e
-	op --cache "$@"
-}
+	eval $(op --cache signin costian)
+fi
+set -e
 
 # Next, get SSH keys and GPG keys
 mkdir -p ~/.ssh
 chmod 0700 ~/.ssh
 if [[ ! -f ~/.ssh/id_ed25519 ]]; then
-	1p get document 5fqgog25ivec34grsyqbofjd6m > ~/.ssh/id_ed25519
-	1p get document lhif5tpa3dm3imo52vdjbrxuci > ~/.ssh/id_ed25519.pub
+	op get document 5fqgog25ivec34grsyqbofjd6m > ~/.ssh/id_ed25519
+	op get document lhif5tpa3dm3imo52vdjbrxuci > ~/.ssh/id_ed25519.pub
+	if [[ "$(uname)" = "Darwin" ]]; then
+		eval $(ssh-agent)
+		ssh-add -K ~/.ssh/id_ed25519
+	fi
 fi
 if [[ ! -f ~/.ssh/id_rsa ]]; then
-	1p get document ig33cy2zkf5zxxlppqenfnoxbu > ~/.ssh/id_rsa
-	1p get document 7gw2rk7ebrlrr3ukidw3n6udp4 > ~/.ssh/id_rsa.pub
+	op get document ig33cy2zkf5zxxlppqenfnoxbu > ~/.ssh/id_rsa
+	op get document 7gw2rk7ebrlrr3ukidw3n6udp4 > ~/.ssh/id_rsa.pub
 fi
 
 set +e
-if [[ ! -f ~/.gnupg/pubring.kbx ]] || gpg --list-keys | grep 77E30DB4F230282981ED38EEDDF677A250F99DFD > /dev/null; then
-	set -e
-	1p get document xhrjl3vs5i22tdiu2lmv7mgq4m | gpg --import -
+if [[ ! -f ~/.gnupg/pubring.kbx ]] || ! gpg --list-keys | grep 77E30DB4F230282981ED38EEDDF677A250F99DFD > /dev/null; then
+	# Allow an error here - just tell the user to retry later on.
+	# The reason is that pinentry may try show up and ask for a password, but then fail to do so
+	op get document xhrjl3vs5i22tdiu2lmv7mgq4m | gpg --import -
 	expect -c "spawn gpg --edit-key 77E30DB4F230282981ED38EEDDF677A250F99DFD trust quit; send \"5\ry\r\"; expect eof"
+	set -e
 else
 	set -e
 fi
@@ -46,21 +47,21 @@ fi
 if [[ ! -f ~/.config/tizonia/tizonia.conf ]]; then
 	mkdir -p ~/.config/tizonia
 	chmod 0700 ~/.config/tizonia
-	1p get document c62c6tfbybglmxnavvtpqqhjry > ~/.config/tizonia/tizonia.conf
+	op get document c62c6tfbybglmxnavvtpqqhjry > ~/.config/tizonia/tizonia.conf
 fi
 
 # Add software licenses
 if [[ -d ~/.config/sublime-text-3 && ! -f ~/.config/sublime-text-3/Local/License.sublime_license ]]; then
 	mkdir -p ~/.config/sublime-text-3/Local
-	1p get item Sublime\ Text | jq '.details.sections[0].fields[1].v' -r > ~/.config/sublime-text-3/Local/License.sublime_license
+	op get item Sublime\ Text | jq '.details.sections[0].fields[1].v' -r > ~/.config/sublime-text-3/Local/License.sublime_license
 fi
 
 # Log in to apps
 if ! npm whoami > /dev/null 2>&1; then
-	NPM_LOGIN_DETAILS="$(1p get item npm | jq '.details.fields')"
+	NPM_LOGIN_DETAILS="$(op get item npm | jq '.details.fields')"
 	NPM_USERNAME="$(echo $NPM_LOGIN_DETAILS | jq -r '.[] | select(.name == "username").value')"
 	NPM_PASSWORD="$(echo $NPM_LOGIN_DETAILS | jq -r '.[] | select(.name == "password").value')"
-	NPM_TOTP="$(1p get totp npm)"
+	NPM_TOTP="$(op get totp npm)"
 	expect <<EOE
 spawn npm adduser
 expect {
@@ -73,7 +74,7 @@ EOE
 fi
 
 # Log in to docker. Not sure if logged in or not, so just log out, and then log in :)
-DOCKER_LOGIN_DETAILS="$(1p get item 'Docker Hub' | jq '.details.fields')"
+DOCKER_LOGIN_DETAILS="$(op get item 'Docker Hub' | jq '.details.fields')"
 set +e # Not needed right now, but docker could make docker logout (when you aren't really logged in) throw an error
 docker logout > /dev/null 2> /dev/null
 # Try logging in
@@ -96,11 +97,11 @@ set -e
 
 # Import SSH config
 if [[ ! -f ~/.ssh/config ]]; then
-	1p get document "SSH Config" > ~/.ssh/config
+	op get document "SSH Config" > ~/.ssh/config
 else
 	TMPDIR="$(mktemp -d)"
 	mv ~/.ssh/config "$TMPDIR"
-	1p get document "SSH Config" > ~/.ssh/config
+	op get document "SSH Config" > ~/.ssh/config
 	# Delete the temporary stuff if there are no differences at all
 	if cmp "$TMPDIR/config" ~/.ssh/config > /dev/null; then
 		rm -Rf "$TMPDIR/config"
@@ -115,9 +116,9 @@ if [[ "$(uname)" != "Darwin" ]]; then
 	# First, find the wifi interface, and only proceed if there actually is one
 	WIFI_IFNAME=`nmcli d | grep '\swifi\s' | awk '{print $1}'`
 	if [[ ! -z "$WIFI_IFNAME" ]]; then
-		for WIFI_UUID in $(1p list items | jq '.[] | select(.templateUuid == "109").uuid' -r); do
-			WIFI_JSON="$(1p get item $WIFI_UUID)"
-			# Name is the name in 1Password, not the SSID of the actual WiFi AP
+		for WIFI_UUID in $(op list items | jq '.[] | select(.templateUuid == "109").uuid' -r); do
+			WIFI_JSON="$(op get item $WIFI_UUID)"
+			# Name is the name in 1password, not the SSID of the actual WiFi AP
 			WIFI_NAME="$(echo $WIFI_JSON | jq '.overview.title' -r)"
 			# Now get the credentials for logging into the router
 			WIFI_LOGIN_JSON="$(echo $WIFI_JSON | jq '.details.sections | .[] | select(has("fields")).fields | .[]')"
diff --git a/scripts-james/helpers/setup-non-multitenant b/scripts-james/helpers/setup-non-multitenant
--- a/scripts-james/helpers/setup-non-multitenant
+++ b/scripts-james/helpers/setup-non-multitenant
@@ -2,11 +2,17 @@
 set -eo pipefail
 cd "$(dirname "$0")"
 if [ "$(uname)" = "Darwin" ]; then
+	set +e
 	softwareupdate --install-rosetta
+	set -e
 	if [[ ! -f /opt/homebrew/bin/brew ]]; then
+		FIRST_TIME_INSTALLING=true
 		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+		eval "$(/opt/homebrew/bin/brew shellenv)"
 	fi
 	brew bundle --cleanup --file="$HOME/.config/Brewfile$MULTITENANT_SUFFIX"
+	# Installing from the Brewfile will include Xcode - you need to accept Xcode's license!
+	[[ "$FIRST_TIME_INSTALLING" = "true" ]] && sudo xcodebuild -license
 	# brew + zsh will make /opt/homebrew/share/zsh and /opt/homebrew/share/zsh/site-functions be group-writable, which compaudit complains about
 	chmod g-w /opt/homebrew/share/zsh/site-functions
 	chmod g-w /opt/homebrew/share/zsh
@@ -51,4 +57,18 @@ if [ "$(uname)" != "Darwin" ]; then
 	fi
 	chmod 0775 /usr/lib/node_modules
 	chmod 0775 /usr/lib/bin
+else
+	./tweak-macos-defaults
 fi
+
+if ! gpg --list-keys | grep 77E30DB4F230282981ED38EEDDF677A250F99DFD > /dev/null; then
+	echo
+	echo
+	echo "Importing GPG keys failed! Try running this manually:"
+	echo '  eval $(op --cache signin costian)'
+	echo "  op get document xhrjl3vs5i22tdiu2lmv7mgq4m | gpg --import -"
+	echo '  expect -c "spawn gpg --edit-key 77E30DB4F230282981ED38EEDDF677A250F99DFD trust quit; send \"5\ry\r\"; expect eof"'
+	echo
+fi
+
+echo "Successfully set up! If this is your initial setup, open a new terminal tab now"
